### PR TITLE
Update eth-tester[py-evm] dependency

### LINKED ISSUE #42: Update py-evm / web3 dependencies
Update dependencies of `eth-tester[py-evm]` and `web3` if possible. Notably to fix vulnerability in `cryptography<3.2` (https://github.com/advisories/GHSA-hggm-jpg3-v476) in currently required version of `eth-tester[py-evm]`

### PR DESCRIPTION
**Pull request by cducrest**
This allows to no longer use vulnerable dependency cryptography<3.2.
Update tests to work with newer version of web3 (it's mostly overriding some new tests of web3).

closes https://github.com/voith/eth-tester-rpc/issues/42

### CODE REVIEW

**Comment by voith** [comment]
@cducrest I'm sorry, I completely forgot about this issue. I can take a look at this PR tomorrow. 
Also, If you're interested in this project then I could add you as a maintainer to the repo. I no longer use this project and don't get enough time to work further on it.

**Review by voith — COMMENTED** [review]
Thank you for this contribution. LGTM! I have tested it. However, there was one failing test which I've fixed in #44.

**Comment by voith** [comment]
merged in #44. Thank you for your contribution.

**Comment by cducrest** [comment]
I'm not sure how well I can maintain this ad I'm often confused with the many intertwined parts of the web3 ecosystem. The only PR left I would probably open would be to add an option to disable printing if I ever come to it.

**Comment by voith** [comment]
> I'm not sure how well I can maintain this ad I'm often confused with the many intertwined parts of the web3 ecosystem.

@cducrest I totally understand. All I can promise is that I will review and test any PRs that are raised. 

> The only PR left I would probably open would be to add an option to disable printing if I ever come to it.

I'll be glad to merge it. I had added those print statements while I was debugging some RPC calls. I forgot to remove them and they got shipped in all releases made hence after.

**Pull request closed without merging**
